### ISSUE TITLE
AU Linux kernel autumn 2016 запрос на проверку linked_lists Суворов Егор

### ISSUE THREAD

**Issue by yeputons** [yeputons/au-linux-kernel-autumn-2016#1]
7422c527d38cc5d28fe35df85e967f264bf6233d

Я понимаю, что дедлайны давным-давно канули в лету, однако если у вас есть возможность - хотелось бы получить feedback.

**Comment by eabatalov** [comment]
Здравствуйте. Задание выполнено отлично.
Единственное, чуть лучше вместо
stack_entry_t\* entry = kmalloc(sizeof(stack_entry_t), GFP_KERNEL);
писать
stack_entry_t\* entry = kmalloc(sizeof(*entry), GFP_KERNEL);
Чтобы не зависить от изменения типа переменной.

**Comment by eabatalov** [comment]
Я поставлю вам 50% баллов за задание.
