### ISSUE TITLE
AU Linux kernel autumn 2016 запрос на проверку vsd1 Суворов Егор 

### ISSUE THREAD

**Issue by yeputons** [yeputons/au-linux-kernel-autumn-2016#2]
3df64a8734682a2ac79e9579ca8030f3da2a0474

Та же просьба, что и раньше: посмотрете, пожалуйста, при наличии возможности.

**Comment by eabatalov** [comment]
Все отлично. Тоже 50% за задание.

**Comment by yeputons** [comment]
@eabatalov Обнаружил спецэффект: если запустить `fdisk /dev/vsd` и вбить команды `o`, `w`, то на устройство всё запишется, однако fdisk ругнётся, что `/dev/vsd: close device failed: Invalid argument`. С чем это может быть связано? Я вставил debug output в write/read/llseek, и вроде бы никто из нех `-EINVAL` не должен возвращать.

**Comment by eabatalov** [comment]
@yeputons  запустите fdisk под strace -f и задампьте весь аутпут в лог, приаттачте к Issue.

**Comment by yeputons** [comment]
@eabatalov <a href="https://gist.github.com/yeputons/2cc03a4c3d05af379c273898e85f25a0">Запустил</a>, обнаружил вызов `fsync`. Он у нас не поддерживается - видимо, поэтому и получался "Invalid argument":

```
open("/dev/vsd", O_RDWR|O_CLOEXEC)      = 3
...
lseek(3, 0, SEEK_SET)                   = 0
write(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 512) = 512
fstat(3, {st_mode=S_IFCHR|0666, st_rdev=makedev(10, 57), ...}) = 0
fsync(3)                                = -1 EINVAL (Invalid argument)
```

А вот если добавить функцию `vsd_dev_fsync` по аналогии с `vsd_dev_open` и прописать её в `vsd_dev_fops`, то всё ок.

Верно ли я понял, что если функция не указана в `vsd_dev_fops`, то она всегда выдаёт `EINVAL`?

**Comment by eabatalov** [comment]
@yeputons да, вы абсолютно правы http://lxr.free-electrons.com/source/fs/sync.c#L187
