### ISSUE TITLE
 AU Linux kernel autumn 2016 запрос на проверку vsd2 Суворов Егор

### ISSUE THREAD

**Issue by yeputons** [yeputons/au-linux-kernel-autumn-2016#3]
b9337a3c21529f649856d48b0b4337b95263d791

Та же просьба, что и раньше: посмотрете, пожалуйста, при наличии возможности.

Кстати, почему мы используем issues с конкретным коммитом вместо pull requests в master из отдельной ветки? Чтобы было зафиксировано множество изменений на момент отправки issue?

**Comment by eabatalov** [comment]
Здравствуйте. Если хотите, можно присылать решение заданий не в виде одного коммита, а в виде pull request'а. Привычка сливать коммиты в один и переделывать историю коммитов для лучшей читаемости патчей берет свои корни в работе в LKML.

**Comment by eabatalov** [comment]
Ошибки незначительные, можно поставить 100% за задание.
-50% за позднюю сдачу.
